[storage]
data_directory = data
brands_sub_dir = brands
category_ids_sub_dir = category_ids
failed_categories_sub_dir  = failed_categories
product_ids_sub_dir = product_ids
products_sub_dir = products
root_categories_sub_dir = root_categories
token_sub_dir = token


[urls]
main_url = https://uzum.uz/ru
graphql_url = https://graphql.uzum.uz/
root_categories_req_url = https://api.uzum.uz/api/main/root-categories?eco=false
product_api_url = https://api.uzum.uz/api/v2/product/